/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else



#include <libimobiledevice/libimobiledevice.h>
#include <libimobiledevice/lockdown.h>



        typedef struct IntOut {
            jint value;
        } IntOut;
    
SWIGINTERN struct IntOut *new_IntOut(void){
          return (IntOut *) calloc(1,sizeof(jint));
        }
SWIGINTERN void delete_IntOut(struct IntOut *self){
          ;
          free(self);
        }

        typedef struct StringOut {
            charp value;
        } StringOut;
    
SWIGINTERN struct StringOut *new_StringOut(void){
          return (StringOut *) calloc(1,sizeof(charp));
        }
SWIGINTERN void delete_StringOut(struct StringOut *self){
          if (self->value) free(self->value);
          free(self);
        }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_IntOut_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct IntOut *arg1 = (struct IntOut *) 0 ;
  jint result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct IntOut **)&jarg1; 
  result =  ((arg1)->value);
  jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_new_1IntOut(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct IntOut *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct IntOut *)new_IntOut();
  *(struct IntOut **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_delete_1IntOut(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct IntOut *arg1 = (struct IntOut *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct IntOut **)&jarg1; 
  delete_IntOut(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_StringOut_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct StringOut *arg1 = (struct StringOut *) 0 ;
  charp result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct StringOut **)&jarg1; 
  result =  ((arg1)->value);
  {
    charp * resultptr = (charp *) malloc(sizeof(charp));
    memmove(resultptr, &result, sizeof(charp));
    *(charp **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_new_1StringOut(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct StringOut *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct StringOut *)new_StringOut();
  *(struct StringOut **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_delete_1StringOut(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct StringOut *arg1 = (struct StringOut *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct StringOut **)&jarg1; 
  delete_StringOut(arg1);
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1set_1debug_1level(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  idevice_set_debug_level(arg1);
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1t_1event_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  idevice_event_t *arg1 = (idevice_event_t *) 0 ;
  enum idevice_event_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(idevice_event_t **)&jarg1; 
  arg2 = (enum idevice_event_type)jarg2; 
  if (arg1) (arg1)->event = arg2;
}


SWIGEXPORT jint JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1t_1event_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  idevice_event_t *arg1 = (idevice_event_t *) 0 ;
  enum idevice_event_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(idevice_event_t **)&jarg1; 
  result = (enum idevice_event_type) ((arg1)->event);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1t_1udid_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  idevice_event_t *arg1 = (idevice_event_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(idevice_event_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->udid = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->udid, (const char *)arg2);
    } else {
      arg1->udid = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1t_1udid_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  idevice_event_t *arg1 = (idevice_event_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(idevice_event_t **)&jarg1; 
  result = (char *) ((arg1)->udid);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1t_1conn_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  idevice_event_t *arg1 = (idevice_event_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(idevice_event_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->conn_type = arg2;
}


SWIGEXPORT jint JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1t_1conn_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  idevice_event_t *arg1 = (idevice_event_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(idevice_event_t **)&jarg1; 
  result = (int) ((arg1)->conn_type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_new_1idevice_1event_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  idevice_event_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (idevice_event_t *)calloc(1, sizeof(idevice_event_t));
  *(idevice_event_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_delete_1idevice_1event_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  idevice_event_t *arg1 = (idevice_event_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_event_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1subscribe(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  idevice_event_cb_t arg1 = (idevice_event_cb_t) 0 ;
  void *arg2 = (void *) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_event_cb_t *)&jarg1; 
  arg2 = *(void **)&jarg2; 
  result = (idevice_error_t)idevice_event_subscribe(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1event_1unsubscribe(JNIEnv *jenv, jclass jcls) {
  jshort jresult = 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  result = (idevice_error_t)idevice_event_unsubscribe();
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1get_1device_1list(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jshort jresult = 0 ;
  char ***arg1 = (char ***) 0 ;
  int *arg2 = (int *) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(char ****)&jarg1; 
  arg2 = *(int **)&jarg2; 
  result = (idevice_error_t)idevice_get_device_list(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1device_1list_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  char **arg1 = (char **) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  result = (idevice_error_t)idevice_device_list_free(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1new(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jshort jresult = 0 ;
  idevice_t *arg1 = (idevice_t *) 0 ;
  char *arg2 = (char *) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (idevice_error_t)idevice_new(arg1,(char const *)arg2);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  idevice_t arg1 = (idevice_t) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_t *)&jarg1; 
  result = (idevice_error_t)idevice_free(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1connect(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2, jlong jarg3) {
  jshort jresult = 0 ;
  idevice_t arg1 = (idevice_t) 0 ;
  uint16_t arg2 ;
  idevice_connection_t *arg3 = (idevice_connection_t *) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_t *)&jarg1; 
  arg2 = (uint16_t)jarg2; 
  arg3 = *(idevice_connection_t **)&jarg3; 
  result = (idevice_error_t)idevice_connect(arg1,arg2,arg3);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1disconnect(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  idevice_connection_t arg1 = (idevice_connection_t) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_connection_t *)&jarg1; 
  result = (idevice_error_t)idevice_disconnect(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1connection_1send(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jshort jresult = 0 ;
  idevice_connection_t arg1 = (idevice_connection_t) 0 ;
  char *arg2 = (char *) 0 ;
  uint32_t arg3 ;
  uint32_t *arg4 = (uint32_t *) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  arg1 = *(idevice_connection_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (uint32_t)jarg3; 
  arg4 = *(uint32_t **)&jarg4; 
  result = (idevice_error_t)idevice_connection_send(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1connection_1receive_1timeout(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jlong jarg4, jobject jarg4_, jlong jarg5) {
  jshort jresult = 0 ;
  idevice_connection_t arg1 = (idevice_connection_t) 0 ;
  char *arg2 = (char *) 0 ;
  uint32_t arg3 ;
  uint32_t *arg4 = (uint32_t *) 0 ;
  unsigned int arg5 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  arg1 = *(idevice_connection_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (uint32_t)jarg3; 
  arg4 = *(uint32_t **)&jarg4; 
  arg5 = (unsigned int)jarg5; 
  result = (idevice_error_t)idevice_connection_receive_timeout(arg1,arg2,arg3,arg4,arg5);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1connection_1receive(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jshort jresult = 0 ;
  idevice_connection_t arg1 = (idevice_connection_t) 0 ;
  char *arg2 = (char *) 0 ;
  uint32_t arg3 ;
  uint32_t *arg4 = (uint32_t *) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  arg1 = *(idevice_connection_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (uint32_t)jarg3; 
  arg4 = *(uint32_t **)&jarg4; 
  result = (idevice_error_t)idevice_connection_receive(arg1,arg2,arg3,arg4);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1get_1handle(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jshort jresult = 0 ;
  idevice_t arg1 = (idevice_t) 0 ;
  uint32_t *arg2 = (uint32_t *) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(idevice_t *)&jarg1; 
  arg2 = *(uint32_t **)&jarg2; 
  result = (idevice_error_t)idevice_get_handle(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_idevice_1get_1udid(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  idevice_t arg1 = (idevice_t) 0 ;
  char **arg2 = (char **) 0 ;
  idevice_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_t *)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (idevice_error_t)idevice_get_udid(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1device_1certificate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->device_certificate);
    if (arg2) {
      arg1->device_certificate = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->device_certificate, (const char *)arg2);
    } else {
      arg1->device_certificate = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1device_1certificate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  result = (char *) ((arg1)->device_certificate);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1host_1certificate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->host_certificate);
    if (arg2) {
      arg1->host_certificate = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->host_certificate, (const char *)arg2);
    } else {
      arg1->host_certificate = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1host_1certificate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  result = (char *) ((arg1)->host_certificate);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1host_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->host_id);
    if (arg2) {
      arg1->host_id = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->host_id, (const char *)arg2);
    } else {
      arg1->host_id = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1host_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  result = (char *) ((arg1)->host_id);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1root_1certificate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->root_certificate);
    if (arg2) {
      arg1->root_certificate = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->root_certificate, (const char *)arg2);
    } else {
      arg1->root_certificate = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair_1record_1root_1certificate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  result = (char *) ((arg1)->root_certificate);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_new_1lockdownd_1pair_1record(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct lockdownd_pair_record *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct lockdownd_pair_record *)calloc(1, sizeof(struct lockdownd_pair_record));
  *(struct lockdownd_pair_record **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_delete_1lockdownd_1pair_1record(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct lockdownd_pair_record *arg1 = (struct lockdownd_pair_record *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct lockdownd_pair_record **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1service_1descriptor_1port_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  struct lockdownd_service_descriptor *arg1 = (struct lockdownd_service_descriptor *) 0 ;
  uint16_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_service_descriptor **)&jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->port = arg2;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1service_1descriptor_1port_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  struct lockdownd_service_descriptor *arg1 = (struct lockdownd_service_descriptor *) 0 ;
  uint16_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_service_descriptor **)&jarg1; 
  result = (uint16_t) ((arg1)->port);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1service_1descriptor_1ssl_1enabled_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct lockdownd_service_descriptor *arg1 = (struct lockdownd_service_descriptor *) 0 ;
  uint8_t arg2 ;
  uint8_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_service_descriptor **)&jarg1; 
  argp2 = *(uint8_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->ssl_enabled = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1service_1descriptor_1ssl_1enabled_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct lockdownd_service_descriptor *arg1 = (struct lockdownd_service_descriptor *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct lockdownd_service_descriptor **)&jarg1; 
  result =  ((arg1)->ssl_enabled);
  {
    uint8_t * resultptr = (uint8_t *) malloc(sizeof(uint8_t));
    memmove(resultptr, &result, sizeof(uint8_t));
    *(uint8_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_new_1lockdownd_1service_1descriptor(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct lockdownd_service_descriptor *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct lockdownd_service_descriptor *)calloc(1, sizeof(struct lockdownd_service_descriptor));
  *(struct lockdownd_service_descriptor **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_delete_1lockdownd_1service_1descriptor(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct lockdownd_service_descriptor *arg1 = (struct lockdownd_service_descriptor *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct lockdownd_service_descriptor **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1client_1new(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jshort jresult = 0 ;
  idevice_t arg1 = (idevice_t) 0 ;
  lockdownd_client_t *arg2 = (lockdownd_client_t *) 0 ;
  char *arg3 = (char *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_t *)&jarg1; 
  arg2 = *(lockdownd_client_t **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (lockdownd_error_t)lockdownd_client_new(arg1,arg2,(char const *)arg3);
  jresult = (jshort)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1client_1new_1with_1handshake(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jshort jresult = 0 ;
  idevice_t arg1 = (idevice_t) 0 ;
  lockdownd_client_t *arg2 = (lockdownd_client_t *) 0 ;
  char *arg3 = (char *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(idevice_t *)&jarg1; 
  arg2 = *(lockdownd_client_t **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (lockdownd_error_t)lockdownd_client_new_with_handshake(arg1,arg2,(char const *)arg3);
  jresult = (jshort)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1client_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  result = (lockdownd_error_t)lockdownd_client_free(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1query_1type(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char **arg2 = (char **) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (lockdownd_error_t)lockdownd_query_type(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1get_1value(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  plist_t *arg4 = (plist_t *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(plist_t **)&jarg4; 
  result = (lockdownd_error_t)lockdownd_get_value(arg1,(char const *)arg2,(char const *)arg3,arg4);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1set_1value(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  plist_t arg4 ;
  plist_t *argp4 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  argp4 = *(plist_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null plist_t");
    return 0;
  }
  arg4 = *argp4; 
  result = (lockdownd_error_t)lockdownd_set_value(arg1,(char const *)arg2,(char const *)arg3,arg4);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1remove_1value(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (lockdownd_error_t)lockdownd_remove_value(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1start_1service(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char *arg2 = (char *) 0 ;
  lockdownd_service_descriptor_t *arg3 = (lockdownd_service_descriptor_t *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(lockdownd_service_descriptor_t **)&jarg3; 
  result = (lockdownd_error_t)lockdownd_start_service(arg1,(char const *)arg2,arg3);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1start_1session(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4, jobject jarg4_) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char *arg2 = (char *) 0 ;
  char **arg3 = (char **) 0 ;
  int *arg4 = (int *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg4_;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(char ***)&jarg3; 
  arg4 = *(int **)&jarg4; 
  result = (lockdownd_error_t)lockdownd_start_session(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1stop_1session(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char *arg2 = (char *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (lockdownd_error_t)lockdownd_stop_session(arg1,(char const *)arg2);
  jresult = (jshort)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1send(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  plist_t arg2 ;
  plist_t *argp2 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  argp2 = *(plist_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null plist_t");
    return 0;
  }
  arg2 = *argp2; 
  result = (lockdownd_error_t)lockdownd_send(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1receive(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  plist_t *arg2 = (plist_t *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(plist_t **)&jarg2; 
  result = (lockdownd_error_t)lockdownd_receive(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1pair(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  lockdownd_pair_record_t arg2 = (lockdownd_pair_record_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(lockdownd_pair_record_t *)&jarg2; 
  result = (lockdownd_error_t)lockdownd_pair(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1validate_1pair(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  lockdownd_pair_record_t arg2 = (lockdownd_pair_record_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(lockdownd_pair_record_t *)&jarg2; 
  result = (lockdownd_error_t)lockdownd_validate_pair(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1unpair(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  lockdownd_pair_record_t arg2 = (lockdownd_pair_record_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(lockdownd_pair_record_t *)&jarg2; 
  result = (lockdownd_error_t)lockdownd_unpair(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1activate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  plist_t arg2 ;
  plist_t *argp2 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  argp2 = *(plist_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null plist_t");
    return 0;
  }
  arg2 = *argp2; 
  result = (lockdownd_error_t)lockdownd_activate(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1deactivate(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  result = (lockdownd_error_t)lockdownd_deactivate(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1enter_1recovery(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  result = (lockdownd_error_t)lockdownd_enter_recovery(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1goodbye(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  result = (lockdownd_error_t)lockdownd_goodbye(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1client_1set_1label(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  lockdownd_client_set_label(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1get_1device_1udid(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char **arg2 = (char **) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (lockdownd_error_t)lockdownd_get_device_udid(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1get_1device_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char **arg2 = (char **) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (lockdownd_error_t)lockdownd_get_device_name(arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1get_1sync_1data_1classes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jobject jarg3_) {
  jshort jresult = 0 ;
  lockdownd_client_t arg1 = (lockdownd_client_t) 0 ;
  char ***arg2 = (char ***) 0 ;
  int *arg3 = (int *) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(lockdownd_client_t *)&jarg1; 
  arg2 = *(char ****)&jarg2; 
  arg3 = *(int **)&jarg3; 
  result = (lockdownd_error_t)lockdownd_get_sync_data_classes(arg1,arg2,arg3);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1data_1classes_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  char **arg1 = (char **) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  result = (lockdownd_error_t)lockdownd_data_classes_free(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_org_robovm_libimobiledevice_binding_libimobiledeviceJNI_lockdownd_1service_1descriptor_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  lockdownd_service_descriptor_t arg1 = (lockdownd_service_descriptor_t) 0 ;
  lockdownd_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(lockdownd_service_descriptor_t *)&jarg1; 
  result = (lockdownd_error_t)lockdownd_service_descriptor_free(arg1);
  jresult = (jshort)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

