add_definitions(-DPLATFORM_POSIX)
add_definitions(-DPOSIX)
if(LINUX)
  add_definitions(-D_GNU_SOURCE)
endif()

if (ARCH STREQUAL "x86")
  add_definitions(-D_IA32_)
elseif (ARCH STREQUAL "armv6")
elseif (ARCH STREQUAL "armv7")
elseif (ARCH STREQUAL "thumbv6")
elseif (ARCH STREQUAL "thumbv7")
endif()
