/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum AfcFileMode {
  AFC_FOPEN_RDONLY(0x00000001),
  AFC_FOPEN_RW(0x00000002),
  AFC_FOPEN_WRONLY(0x00000003),
  AFC_FOPEN_WR(0x00000004),
  AFC_FOPEN_APPEND(0x00000005),
  AFC_FOPEN_RDAPPEND(0x00000006);

  public final int swigValue() {
    return swigValue;
  }

  public static AfcFileMode swigToEnum(int swigValue) {
    AfcFileMode[] swigValues = AfcFileMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AfcFileMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AfcFileMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AfcFileMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AfcFileMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AfcFileMode(AfcFileMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

