/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum AfcLinkType {
  AFC_HARDLINK(1),
  AFC_SYMLINK(2);

  public final int swigValue() {
    return swigValue;
  }

  public static AfcLinkType swigToEnum(int swigValue) {
    AfcLinkType[] swigValues = AfcLinkType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AfcLinkType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AfcLinkType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AfcLinkType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AfcLinkType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AfcLinkType(AfcLinkType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

