/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum AfcLockOperation {
  AFC_LOCK_SH(1|4),
  AFC_LOCK_EX(2|4),
  AFC_LOCK_UN(8|4);

  public final int swigValue() {
    return swigValue;
  }

  public static AfcLockOperation swigToEnum(int swigValue) {
    AfcLockOperation[] swigValues = AfcLockOperation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AfcLockOperation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AfcLockOperation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AfcLockOperation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AfcLockOperation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AfcLockOperation(AfcLockOperation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

