/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum IDeviceEventType {
  IDEVICE_DEVICE_ADD(1),
  IDEVICE_DEVICE_REMOVE;

  public final int swigValue() {
    return swigValue;
  }

  public static IDeviceEventType swigToEnum(int swigValue) {
    IDeviceEventType[] swigValues = IDeviceEventType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IDeviceEventType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IDeviceEventType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IDeviceEventType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IDeviceEventType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IDeviceEventType(IDeviceEventType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

