/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum IDeviceError {
  IDEVICE_E_SUCCESS(0),
  IDEVICE_E_INVALID_ARG(-1),
  IDEVICE_E_UNKNOWN_ERROR(-2),
  IDEVICE_E_NO_DEVICE(-3),
  IDEVICE_E_NOT_ENOUGH_DATA(-4),
  IDEVICE_E_BAD_HEADER(-5),
  IDEVICE_E_SSL_ERROR(-6);

  public final int swigValue() {
    return swigValue;
  }

  public static IDeviceError swigToEnum(int swigValue) {
    IDeviceError[] swigValues = IDeviceError.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IDeviceError swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IDeviceError.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IDeviceError() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IDeviceError(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IDeviceError(IDeviceError swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

