/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum InstProxyError {
  INSTPROXY_E_SUCCESS(0),
  INSTPROXY_E_INVALID_ARG(-1),
  INSTPROXY_E_PLIST_ERROR(-2),
  INSTPROXY_E_CONN_FAILED(-3),
  INSTPROXY_E_OP_IN_PROGRESS(-4),
  INSTPROXY_E_OP_FAILED(-5),
  INSTPROXY_E_RECEIVE_TIMEOUT(-6),
  INSTPROXY_E_UNKNOWN_ERROR(-256);

  public final int swigValue() {
    return swigValue;
  }

  public static InstProxyError swigToEnum(int swigValue) {
    InstProxyError[] swigValues = InstProxyError.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (InstProxyError swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + InstProxyError.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private InstProxyError() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private InstProxyError(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private InstProxyError(InstProxyError swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

