/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public interface LibIMobileDeviceConstants {
  public final static String AFC_SERVICE_NAME = "com.apple.afc";
  public final static String INSTPROXY_SERVICE_NAME = "com.apple.mobile.installation_proxy";
  public final static String MOBILE_IMAGE_MOUNTER_SERVICE_NAME = "com.apple.mobile.mobile_image_mounter";
}
