/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public class LockdowndServiceDescriptorStructOut {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LockdowndServiceDescriptorStructOut(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LockdowndServiceDescriptorStructOut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibIMobileDeviceJNI.delete_LockdowndServiceDescriptorStructOut(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LockdowndServiceDescriptorStruct getValue() {
    long cPtr = LibIMobileDeviceJNI.LockdowndServiceDescriptorStructOut_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LockdowndServiceDescriptorStruct(cPtr, false);
  }

  public LockdowndServiceDescriptorStructOut() {
    this(LibIMobileDeviceJNI.new_LockdowndServiceDescriptorStructOut(), true);
  }

}
