#!/bin/bash
#
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

# We compile for a 1.4 target to suppress the use of EnclosingMethod
# attributes.
mkdir classes
${JAVAC} -source 1.4 -target 1.4 -d classes `find src -name '*.java'`

# Suppress stderr to keep the inner class warnings out of the expected output.
dx --debug --dex --dump-to=classes.lst --output=classes.dex \
    --dump-width=1000 classes 2>/dev/null

zip test.jar classes.dex
