/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public enum AtomicOrdering {
  AtomicOrderingNotAtomic(0),
  AtomicOrderingUnordered(1),
  AtomicOrderingMonotonic(2),
  AtomicOrderingAcquire(4),
  AtomicOrderingRelease(5),
  AtomicOrderingAcquireRelease(6),
  AtomicOrderingSequentiallyConsistent(7);

  public final int swigValue() {
    return swigValue;
  }

  public static AtomicOrdering swigToEnum(int swigValue) {
    AtomicOrdering[] swigValues = AtomicOrdering.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AtomicOrdering swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AtomicOrdering.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AtomicOrdering() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AtomicOrdering(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AtomicOrdering(AtomicOrdering swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

