/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public enum CodeModel {
  CodeModelDefault,
  CodeModelJITDefault,
  CodeModelSmall,
  CodeModelKernel,
  CodeModelMedium,
  CodeModelLarge;

  public final int swigValue() {
    return swigValue;
  }

  public static CodeModel swigToEnum(int swigValue) {
    CodeModel[] swigValues = CodeModel.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CodeModel swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CodeModel.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CodeModel() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CodeModel(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CodeModel(CodeModel swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

