/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public class ModuleProviderRefOut {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ModuleProviderRefOut(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModuleProviderRefOut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LLVMJNI.delete_ModuleProviderRefOut(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModuleProviderRef getValue() {
    long cPtr = LLVMJNI.ModuleProviderRefOut_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ModuleProviderRef(cPtr, false);
  }

  public ModuleProviderRefOut() {
    this(LLVMJNI.new_ModuleProviderRefOut(), true);
  }

}
