/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.llvm.binding;

public enum TypeKind {
  VoidTypeKind,
  HalfTypeKind,
  FloatTypeKind,
  DoubleTypeKind,
  X86_FP80TypeKind,
  FP128TypeKind,
  PPC_FP128TypeKind,
  LabelTypeKind,
  IntegerTypeKind,
  FunctionTypeKind,
  StructTypeKind,
  ArrayTypeKind,
  PointerTypeKind,
  VectorTypeKind,
  MetadataTypeKind,
  X86_MMXTypeKind;

  public final int swigValue() {
    return swigValue;
  }

  public static TypeKind swigToEnum(int swigValue) {
    TypeKind[] swigValues = TypeKind.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (TypeKind swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + TypeKind.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private TypeKind() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private TypeKind(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private TypeKind(TypeKind swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

