package: org.robovm.apple.systemconfiguration
include: [foundation.yaml, corefoundation.yaml, dispatch.yaml]
library: SystemConfiguration
framework: SystemConfiguration
clang_args: ['-x', 'objective-c']
headers:
    - /System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h
typedefs:
    SCNetworkReachabilityRef: SCNetworkReachability
private_typedefs:
    '__CFString *': String
    '__CFString **': 'NSString.NSStringPtr'
    '__CFData *': NSData
    '__CFURL *': NSURL
    '__CFDictionary *': 'NSDictionary<?, ?>'
    '__CFArray *': 'NSArray<?>'
    '__CFError *': NSError
    
enums:
    SCStatusCode: { first: kSCStatusOK }
    SCNetworkReachabilityFlags: { first: kSCNetworkReachabilityFlagsTransientConnection, bits: true, marshaler: Bits.AsMachineSizedIntMarshaler }
        
classes:
    __SCNetworkReachability:
        name: SCNetworkReachability
        extends: CFType
    SCNetworkReachabilityContext:
        visibility: ''
        info:
            type: '@Pointer long'

protocols: {}

functions:
    (SC.*)GetTypeID:
        class: '#{g[0]}'
        name: getClassTypeID
 
    # SCNetworkReachability
    SCNetworkReachability(Create).*:
        class: SCNetworkReachability
        name: '#{g[0]}'
        visibility: private
        return_marshaler: CFType.NoRetainMarshaler
        parameters:
            address:
                type: 'Struct<?>'
            localAddress:
                type: 'Struct<?>'
            remoteAddress:
                type: 'Struct<?>'
    SCNetworkReachability(GetFlags):
        class: SCNetworkReachability
        name: '#{g[0]}'
        visibility: protected
    SCNetworkReachability(SetCallback):
        class: SCNetworkReachability
        name: '#{g[0]}'
        visibility: protected
    SCNetworkReachability(Schedule)WithRunLoop:
        class: SCNetworkReachability
        name: '#{g[0]}'
        parameters:
            runLoopMode:
                type: CFString
    SCNetworkReachability(Unschedule)FromRunLoop:
        class: SCNetworkReachability
        name: '#{g[0]}'
        parameters:
            runLoopMode:
                type: CFString
    SCNetworkReachability(.*):
        class: SCNetworkReachability
        name: '#{g[0]}'

    # SCStatus
    SCCopyLastError:
        class: SCStatus
        name: getLastError
    SCError:
        class: SCStatus
        name: getLastStatus
        return_type: SCStatusCode
    SCErrorString:
        class: SCStatus
        name: getStatusDescription0
        visibility: protected
        parameters:
            status:
                type: SCStatusCode

    # Make sure we don't miss any functions if new ones are introduced in a later version
    (k?SC.*):
        class: SystemConfiguration
        name: 'Function__#{g[0]}'

values:
    # Make sure we don't miss any values if new ones are introduced in a later version
    #(k?SC.*):
    #    class: SystemConfiguration
    #    name: 'Value__#{g[0]}'

constants:
    # Make sure we don't miss any constants if new ones are introduced in a later version
    #(k?SC.*):
    #    class: SystemConfiguration
    #    name: 'Constant__#{g[0]}'
