/* Soot - a J*va Optimization Framework
 * Copyright (C) 2003 Ondrej Lhotak
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/* THIS FILE IS AUTOMATICALLY GENERATED USING soot/make_singletons. DO NOT EDIT! */

package soot;

/** A class to group together all the global variables in Soot. */
public class Singletons {
    public final class Global {
        private Global() {}
    }
    private Global g = new Global();

    private soot.PhaseOptions instance_soot_PhaseOptions;
    public soot.PhaseOptions soot_PhaseOptions() {
        if( instance_soot_PhaseOptions == null ) instance_soot_PhaseOptions = new soot.PhaseOptions( g );
        return instance_soot_PhaseOptions;
    }

    private soot.jimple.toolkits.callgraph.VirtualCalls instance_soot_jimple_toolkits_callgraph_VirtualCalls;
    public soot.jimple.toolkits.callgraph.VirtualCalls soot_jimple_toolkits_callgraph_VirtualCalls() {
        if( instance_soot_jimple_toolkits_callgraph_VirtualCalls == null ) instance_soot_jimple_toolkits_callgraph_VirtualCalls = new soot.jimple.toolkits.callgraph.VirtualCalls( g );
        return instance_soot_jimple_toolkits_callgraph_VirtualCalls;
    }

    private soot.util.SharedBitSetCache instance_soot_util_SharedBitSetCache;
    public soot.util.SharedBitSetCache soot_util_SharedBitSetCache() {
        if( instance_soot_util_SharedBitSetCache == null ) instance_soot_util_SharedBitSetCache = new soot.util.SharedBitSetCache( g );
        return instance_soot_util_SharedBitSetCache;
    }

    private soot.options.Options instance_soot_options_Options;
    public soot.options.Options soot_options_Options() {
        if( instance_soot_options_Options == null ) instance_soot_options_Options = new soot.options.Options( g );
        return instance_soot_options_Options;
    }

    private soot.jimple.toolkits.callgraph.CHATransformer instance_soot_jimple_toolkits_callgraph_CHATransformer;
    public soot.jimple.toolkits.callgraph.CHATransformer soot_jimple_toolkits_callgraph_CHATransformer() {
        if( instance_soot_jimple_toolkits_callgraph_CHATransformer == null ) instance_soot_jimple_toolkits_callgraph_CHATransformer = new soot.jimple.toolkits.callgraph.CHATransformer( g );
        return instance_soot_jimple_toolkits_callgraph_CHATransformer;
    }

    private soot.toolkits.graph.SlowPseudoTopologicalOrderer instance_soot_toolkits_graph_SlowPseudoTopologicalOrderer;
    public soot.toolkits.graph.SlowPseudoTopologicalOrderer soot_toolkits_graph_SlowPseudoTopologicalOrderer() {
        if( instance_soot_toolkits_graph_SlowPseudoTopologicalOrderer == null ) instance_soot_toolkits_graph_SlowPseudoTopologicalOrderer = new soot.toolkits.graph.SlowPseudoTopologicalOrderer( g );
        return instance_soot_toolkits_graph_SlowPseudoTopologicalOrderer;
    }

    private soot.jimple.toolkits.typing.integer.ClassHierarchy instance_soot_jimple_toolkits_typing_integer_ClassHierarchy;
    public soot.jimple.toolkits.typing.integer.ClassHierarchy soot_jimple_toolkits_typing_integer_ClassHierarchy() {
        if( instance_soot_jimple_toolkits_typing_integer_ClassHierarchy == null ) instance_soot_jimple_toolkits_typing_integer_ClassHierarchy = new soot.jimple.toolkits.typing.integer.ClassHierarchy( g );
        return instance_soot_jimple_toolkits_typing_integer_ClassHierarchy;
    }

    private soot.tagkit.TagManager instance_soot_tagkit_TagManager;
    public soot.tagkit.TagManager soot_tagkit_TagManager() {
        if( instance_soot_tagkit_TagManager == null ) instance_soot_tagkit_TagManager = new soot.tagkit.TagManager( g );
        return instance_soot_tagkit_TagManager;
    }

    private soot.jimple.toolkits.pointer.representations.Environment instance_soot_jimple_toolkits_pointer_representations_Environment;
    public soot.jimple.toolkits.pointer.representations.Environment soot_jimple_toolkits_pointer_representations_Environment() {
        if( instance_soot_jimple_toolkits_pointer_representations_Environment == null ) instance_soot_jimple_toolkits_pointer_representations_Environment = new soot.jimple.toolkits.pointer.representations.Environment( g );
        return instance_soot_jimple_toolkits_pointer_representations_Environment;
    }

    private soot.jimple.toolkits.pointer.representations.TypeConstants instance_soot_jimple_toolkits_pointer_representations_TypeConstants;
    public soot.jimple.toolkits.pointer.representations.TypeConstants soot_jimple_toolkits_pointer_representations_TypeConstants() {
        if( instance_soot_jimple_toolkits_pointer_representations_TypeConstants == null ) instance_soot_jimple_toolkits_pointer_representations_TypeConstants = new soot.jimple.toolkits.pointer.representations.TypeConstants( g );
        return instance_soot_jimple_toolkits_pointer_representations_TypeConstants;
    }

    private soot.coffi.Util instance_soot_coffi_Util;
    public soot.coffi.Util soot_coffi_Util() {
        if( instance_soot_coffi_Util == null ) instance_soot_coffi_Util = new soot.coffi.Util( g );
        return instance_soot_coffi_Util;
    }

    private soot.SourceLocator instance_soot_SourceLocator;
    public soot.SourceLocator soot_SourceLocator() {
        if( instance_soot_SourceLocator == null ) instance_soot_SourceLocator = new soot.SourceLocator( g );
        return instance_soot_SourceLocator;
    }

    private soot.coffi.CONSTANT_Utf8_collector instance_soot_coffi_CONSTANT_Utf8_collector;
    public soot.coffi.CONSTANT_Utf8_collector soot_coffi_CONSTANT_Utf8_collector() {
        if( instance_soot_coffi_CONSTANT_Utf8_collector == null ) instance_soot_coffi_CONSTANT_Utf8_collector = new soot.coffi.CONSTANT_Utf8_collector( g );
        return instance_soot_coffi_CONSTANT_Utf8_collector;
    }

    private soot.jimple.toolkits.base.Aggregator instance_soot_jimple_toolkits_base_Aggregator;
    public soot.jimple.toolkits.base.Aggregator soot_jimple_toolkits_base_Aggregator() {
        if( instance_soot_jimple_toolkits_base_Aggregator == null ) instance_soot_jimple_toolkits_base_Aggregator = new soot.jimple.toolkits.base.Aggregator( g );
        return instance_soot_jimple_toolkits_base_Aggregator;
    }

    private soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsChecker instance_soot_jimple_toolkits_annotation_arraycheck_ArrayBoundsChecker;
    public soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsChecker soot_jimple_toolkits_annotation_arraycheck_ArrayBoundsChecker() {
        if( instance_soot_jimple_toolkits_annotation_arraycheck_ArrayBoundsChecker == null ) instance_soot_jimple_toolkits_annotation_arraycheck_ArrayBoundsChecker = new soot.jimple.toolkits.annotation.arraycheck.ArrayBoundsChecker( g );
        return instance_soot_jimple_toolkits_annotation_arraycheck_ArrayBoundsChecker;
    }

    private soot.BooleanType instance_soot_BooleanType;
    public soot.BooleanType soot_BooleanType() {
        if( instance_soot_BooleanType == null ) instance_soot_BooleanType = new soot.BooleanType( g );
        return instance_soot_BooleanType;
    }

    private soot.jimple.toolkits.scalar.pre.BusyCodeMotion instance_soot_jimple_toolkits_scalar_pre_BusyCodeMotion;
    public soot.jimple.toolkits.scalar.pre.BusyCodeMotion soot_jimple_toolkits_scalar_pre_BusyCodeMotion() {
        if( instance_soot_jimple_toolkits_scalar_pre_BusyCodeMotion == null ) instance_soot_jimple_toolkits_scalar_pre_BusyCodeMotion = new soot.jimple.toolkits.scalar.pre.BusyCodeMotion( g );
        return instance_soot_jimple_toolkits_scalar_pre_BusyCodeMotion;
    }

    private soot.ByteType instance_soot_ByteType;
    public soot.ByteType soot_ByteType() {
        if( instance_soot_ByteType == null ) instance_soot_ByteType = new soot.ByteType( g );
        return instance_soot_ByteType;
    }

    private soot.jimple.toolkits.pointer.CastCheckEliminatorDumper instance_soot_jimple_toolkits_pointer_CastCheckEliminatorDumper;
    public soot.jimple.toolkits.pointer.CastCheckEliminatorDumper soot_jimple_toolkits_pointer_CastCheckEliminatorDumper() {
        if( instance_soot_jimple_toolkits_pointer_CastCheckEliminatorDumper == null ) instance_soot_jimple_toolkits_pointer_CastCheckEliminatorDumper = new soot.jimple.toolkits.pointer.CastCheckEliminatorDumper( g );
        return instance_soot_jimple_toolkits_pointer_CastCheckEliminatorDumper;
    }

    private soot.CharType instance_soot_CharType;
    public soot.CharType soot_CharType() {
        if( instance_soot_CharType == null ) instance_soot_CharType = new soot.CharType( g );
        return instance_soot_CharType;
    }

    private soot.jimple.toolkits.annotation.arraycheck.ClassFieldAnalysis instance_soot_jimple_toolkits_annotation_arraycheck_ClassFieldAnalysis;
    public soot.jimple.toolkits.annotation.arraycheck.ClassFieldAnalysis soot_jimple_toolkits_annotation_arraycheck_ClassFieldAnalysis() {
        if( instance_soot_jimple_toolkits_annotation_arraycheck_ClassFieldAnalysis == null ) instance_soot_jimple_toolkits_annotation_arraycheck_ClassFieldAnalysis = new soot.jimple.toolkits.annotation.arraycheck.ClassFieldAnalysis( g );
        return instance_soot_jimple_toolkits_annotation_arraycheck_ClassFieldAnalysis;
    }

    private soot.jimple.toolkits.scalar.CommonSubexpressionEliminator instance_soot_jimple_toolkits_scalar_CommonSubexpressionEliminator;
    public soot.jimple.toolkits.scalar.CommonSubexpressionEliminator soot_jimple_toolkits_scalar_CommonSubexpressionEliminator() {
        if( instance_soot_jimple_toolkits_scalar_CommonSubexpressionEliminator == null ) instance_soot_jimple_toolkits_scalar_CommonSubexpressionEliminator = new soot.jimple.toolkits.scalar.CommonSubexpressionEliminator( g );
        return instance_soot_jimple_toolkits_scalar_CommonSubexpressionEliminator;
    }

    private soot.jimple.toolkits.scalar.ConditionalBranchFolder instance_soot_jimple_toolkits_scalar_ConditionalBranchFolder;
    public soot.jimple.toolkits.scalar.ConditionalBranchFolder soot_jimple_toolkits_scalar_ConditionalBranchFolder() {
        if( instance_soot_jimple_toolkits_scalar_ConditionalBranchFolder == null ) instance_soot_jimple_toolkits_scalar_ConditionalBranchFolder = new soot.jimple.toolkits.scalar.ConditionalBranchFolder( g );
        return instance_soot_jimple_toolkits_scalar_ConditionalBranchFolder;
    }

    private soot.jimple.toolkits.scalar.ConstantPropagatorAndFolder instance_soot_jimple_toolkits_scalar_ConstantPropagatorAndFolder;
    public soot.jimple.toolkits.scalar.ConstantPropagatorAndFolder soot_jimple_toolkits_scalar_ConstantPropagatorAndFolder() {
        if( instance_soot_jimple_toolkits_scalar_ConstantPropagatorAndFolder == null ) instance_soot_jimple_toolkits_scalar_ConstantPropagatorAndFolder = new soot.jimple.toolkits.scalar.ConstantPropagatorAndFolder( g );
        return instance_soot_jimple_toolkits_scalar_ConstantPropagatorAndFolder;
    }

    private soot.jimple.toolkits.scalar.CopyPropagator instance_soot_jimple_toolkits_scalar_CopyPropagator;
    public soot.jimple.toolkits.scalar.CopyPropagator soot_jimple_toolkits_scalar_CopyPropagator() {
        if( instance_soot_jimple_toolkits_scalar_CopyPropagator == null ) instance_soot_jimple_toolkits_scalar_CopyPropagator = new soot.jimple.toolkits.scalar.CopyPropagator( g );
        return instance_soot_jimple_toolkits_scalar_CopyPropagator;
    }

    private soot.jimple.toolkits.graph.CriticalEdgeRemover instance_soot_jimple_toolkits_graph_CriticalEdgeRemover;
    public soot.jimple.toolkits.graph.CriticalEdgeRemover soot_jimple_toolkits_graph_CriticalEdgeRemover() {
        if( instance_soot_jimple_toolkits_graph_CriticalEdgeRemover == null ) instance_soot_jimple_toolkits_graph_CriticalEdgeRemover = new soot.jimple.toolkits.graph.CriticalEdgeRemover( g );
        return instance_soot_jimple_toolkits_graph_CriticalEdgeRemover;
    }

    private soot.Printer instance_soot_Printer;
    public soot.Printer soot_Printer() {
        if( instance_soot_Printer == null ) instance_soot_Printer = new soot.Printer( g );
        return instance_soot_Printer;
    }

    private soot.jimple.toolkits.scalar.DeadAssignmentEliminator instance_soot_jimple_toolkits_scalar_DeadAssignmentEliminator;
    public soot.jimple.toolkits.scalar.DeadAssignmentEliminator soot_jimple_toolkits_scalar_DeadAssignmentEliminator() {
        if( instance_soot_jimple_toolkits_scalar_DeadAssignmentEliminator == null ) instance_soot_jimple_toolkits_scalar_DeadAssignmentEliminator = new soot.jimple.toolkits.scalar.DeadAssignmentEliminator( g );
        return instance_soot_jimple_toolkits_scalar_DeadAssignmentEliminator;
    }

    private soot.coffi.Double2ndHalfType instance_soot_coffi_Double2ndHalfType;
    public soot.coffi.Double2ndHalfType soot_coffi_Double2ndHalfType() {
        if( instance_soot_coffi_Double2ndHalfType == null ) instance_soot_coffi_Double2ndHalfType = new soot.coffi.Double2ndHalfType( g );
        return instance_soot_coffi_Double2ndHalfType;
    }

    private soot.DoubleType instance_soot_DoubleType;
    public soot.DoubleType soot_DoubleType() {
        if( instance_soot_DoubleType == null ) instance_soot_DoubleType = new soot.DoubleType( g );
        return instance_soot_DoubleType;
    }

    private soot.jimple.toolkits.pointer.DumbPointerAnalysis instance_soot_jimple_toolkits_pointer_DumbPointerAnalysis;
    public soot.jimple.toolkits.pointer.DumbPointerAnalysis soot_jimple_toolkits_pointer_DumbPointerAnalysis() {
        if( instance_soot_jimple_toolkits_pointer_DumbPointerAnalysis == null ) instance_soot_jimple_toolkits_pointer_DumbPointerAnalysis = new soot.jimple.toolkits.pointer.DumbPointerAnalysis( g );
        return instance_soot_jimple_toolkits_pointer_DumbPointerAnalysis;
    }

    private soot.ErroneousType instance_soot_ErroneousType;
    public soot.ErroneousType soot_ErroneousType() {
        if( instance_soot_ErroneousType == null ) instance_soot_ErroneousType = new soot.ErroneousType( g );
        return instance_soot_ErroneousType;
    }

    private soot.jimple.toolkits.pointer.FieldRWTagger instance_soot_jimple_toolkits_pointer_FieldRWTagger;
    public soot.jimple.toolkits.pointer.FieldRWTagger soot_jimple_toolkits_pointer_FieldRWTagger() {
        if( instance_soot_jimple_toolkits_pointer_FieldRWTagger == null ) instance_soot_jimple_toolkits_pointer_FieldRWTagger = new soot.jimple.toolkits.pointer.FieldRWTagger( g );
        return instance_soot_jimple_toolkits_pointer_FieldRWTagger;
    }

    private soot.FloatType instance_soot_FloatType;
    public soot.FloatType soot_FloatType() {
        if( instance_soot_FloatType == null ) instance_soot_FloatType = new soot.FloatType( g );
        return instance_soot_FloatType;
    }

    private soot.jimple.toolkits.pointer.FullObjectSet instance_soot_jimple_toolkits_pointer_FullObjectSet;
    public soot.jimple.toolkits.pointer.FullObjectSet soot_jimple_toolkits_pointer_FullObjectSet() {
        if( instance_soot_jimple_toolkits_pointer_FullObjectSet == null ) instance_soot_jimple_toolkits_pointer_FullObjectSet = new soot.jimple.toolkits.pointer.FullObjectSet( g );
        return instance_soot_jimple_toolkits_pointer_FullObjectSet;
    }

    private soot.IntType instance_soot_IntType;
    public soot.IntType soot_IntType() {
        if( instance_soot_IntType == null ) instance_soot_IntType = new soot.IntType( g );
        return instance_soot_IntType;
    }

    private soot.jimple.Jimple instance_soot_jimple_Jimple;
    public soot.jimple.Jimple soot_jimple_Jimple() {
        if( instance_soot_jimple_Jimple == null ) instance_soot_jimple_Jimple = new soot.jimple.Jimple( g );
        return instance_soot_jimple_Jimple;
    }

    private soot.jimple.toolkits.scalar.pre.LazyCodeMotion instance_soot_jimple_toolkits_scalar_pre_LazyCodeMotion;
    public soot.jimple.toolkits.scalar.pre.LazyCodeMotion soot_jimple_toolkits_scalar_pre_LazyCodeMotion() {
        if( instance_soot_jimple_toolkits_scalar_pre_LazyCodeMotion == null ) instance_soot_jimple_toolkits_scalar_pre_LazyCodeMotion = new soot.jimple.toolkits.scalar.pre.LazyCodeMotion( g );
        return instance_soot_jimple_toolkits_scalar_pre_LazyCodeMotion;
    }

    private soot.tagkit.InnerClassTagAggregator instance_soot_tagkit_InnerClassTagAggregator;
    public soot.tagkit.InnerClassTagAggregator soot_tagkit_InnerClassTagAggregator() {
        if( instance_soot_tagkit_InnerClassTagAggregator == null ) instance_soot_tagkit_InnerClassTagAggregator = new soot.tagkit.InnerClassTagAggregator( g );
        return instance_soot_tagkit_InnerClassTagAggregator;
    }

    private soot.jimple.toolkits.annotation.LineNumberAdder instance_soot_jimple_toolkits_annotation_LineNumberAdder;
    public soot.jimple.toolkits.annotation.LineNumberAdder soot_jimple_toolkits_annotation_LineNumberAdder() {
        if( instance_soot_jimple_toolkits_annotation_LineNumberAdder == null ) instance_soot_jimple_toolkits_annotation_LineNumberAdder = new soot.jimple.toolkits.annotation.LineNumberAdder( g );
        return instance_soot_jimple_toolkits_annotation_LineNumberAdder;
    }

    private soot.jimple.toolkits.scalar.LocalNameStandardizer instance_soot_jimple_toolkits_scalar_LocalNameStandardizer;
    public soot.jimple.toolkits.scalar.LocalNameStandardizer soot_jimple_toolkits_scalar_LocalNameStandardizer() {
        if( instance_soot_jimple_toolkits_scalar_LocalNameStandardizer == null ) instance_soot_jimple_toolkits_scalar_LocalNameStandardizer = new soot.jimple.toolkits.scalar.LocalNameStandardizer( g );
        return instance_soot_jimple_toolkits_scalar_LocalNameStandardizer;
    }

    private soot.toolkits.scalar.LocalPacker instance_soot_toolkits_scalar_LocalPacker;
    public soot.toolkits.scalar.LocalPacker soot_toolkits_scalar_LocalPacker() {
        if( instance_soot_toolkits_scalar_LocalPacker == null ) instance_soot_toolkits_scalar_LocalPacker = new soot.toolkits.scalar.LocalPacker( g );
        return instance_soot_toolkits_scalar_LocalPacker;
    }

    private soot.toolkits.scalar.LocalSplitter instance_soot_toolkits_scalar_LocalSplitter;
    public soot.toolkits.scalar.LocalSplitter soot_toolkits_scalar_LocalSplitter() {
        if( instance_soot_toolkits_scalar_LocalSplitter == null ) instance_soot_toolkits_scalar_LocalSplitter = new soot.toolkits.scalar.LocalSplitter( g );
        return instance_soot_toolkits_scalar_LocalSplitter;
    }

    private soot.coffi.Long2ndHalfType instance_soot_coffi_Long2ndHalfType;
    public soot.coffi.Long2ndHalfType soot_coffi_Long2ndHalfType() {
        if( instance_soot_coffi_Long2ndHalfType == null ) instance_soot_coffi_Long2ndHalfType = new soot.coffi.Long2ndHalfType( g );
        return instance_soot_coffi_Long2ndHalfType;
    }

    private soot.LongType instance_soot_LongType;
    public soot.LongType soot_LongType() {
        if( instance_soot_LongType == null ) instance_soot_LongType = new soot.LongType( g );
        return instance_soot_LongType;
    }

    private soot.jimple.toolkits.scalar.NopEliminator instance_soot_jimple_toolkits_scalar_NopEliminator;
    public soot.jimple.toolkits.scalar.NopEliminator soot_jimple_toolkits_scalar_NopEliminator() {
        if( instance_soot_jimple_toolkits_scalar_NopEliminator == null ) instance_soot_jimple_toolkits_scalar_NopEliminator = new soot.jimple.toolkits.scalar.NopEliminator( g );
        return instance_soot_jimple_toolkits_scalar_NopEliminator;
    }

    private soot.jimple.NullConstant instance_soot_jimple_NullConstant;
    public soot.jimple.NullConstant soot_jimple_NullConstant() {
        if( instance_soot_jimple_NullConstant == null ) instance_soot_jimple_NullConstant = new soot.jimple.NullConstant( g );
        return instance_soot_jimple_NullConstant;
    }

    private soot.jimple.toolkits.annotation.nullcheck.NullPointerChecker instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerChecker;
    public soot.jimple.toolkits.annotation.nullcheck.NullPointerChecker soot_jimple_toolkits_annotation_nullcheck_NullPointerChecker() {
        if( instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerChecker == null ) instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerChecker = new soot.jimple.toolkits.annotation.nullcheck.NullPointerChecker( g );
        return instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerChecker;
    }

    private soot.NullType instance_soot_NullType;
    public soot.NullType soot_NullType() {
        if( instance_soot_NullType == null ) instance_soot_NullType = new soot.NullType( g );
        return instance_soot_NullType;
    }

    private soot.PackManager instance_soot_PackManager;
    public soot.PackManager soot_PackManager() {
        if( instance_soot_PackManager == null ) instance_soot_PackManager = new soot.PackManager( g );
        return instance_soot_PackManager;
    }

    private soot.jimple.toolkits.annotation.profiling.ProfilingGenerator instance_soot_jimple_toolkits_annotation_profiling_ProfilingGenerator;
    public soot.jimple.toolkits.annotation.profiling.ProfilingGenerator soot_jimple_toolkits_annotation_profiling_ProfilingGenerator() {
        if( instance_soot_jimple_toolkits_annotation_profiling_ProfilingGenerator == null ) instance_soot_jimple_toolkits_annotation_profiling_ProfilingGenerator = new soot.jimple.toolkits.annotation.profiling.ProfilingGenerator( g );
        return instance_soot_jimple_toolkits_annotation_profiling_ProfilingGenerator;
    }

    private soot.jimple.toolkits.annotation.arraycheck.RectangularArrayFinder instance_soot_jimple_toolkits_annotation_arraycheck_RectangularArrayFinder;
    public soot.jimple.toolkits.annotation.arraycheck.RectangularArrayFinder soot_jimple_toolkits_annotation_arraycheck_RectangularArrayFinder() {
        if( instance_soot_jimple_toolkits_annotation_arraycheck_RectangularArrayFinder == null ) instance_soot_jimple_toolkits_annotation_arraycheck_RectangularArrayFinder = new soot.jimple.toolkits.annotation.arraycheck.RectangularArrayFinder( g );
        return instance_soot_jimple_toolkits_annotation_arraycheck_RectangularArrayFinder;
    }

    private soot.RefType instance_soot_RefType;
    public soot.RefType soot_RefType() {
        if( instance_soot_RefType == null ) instance_soot_RefType = new soot.RefType( g );
        return instance_soot_RefType;
    }

    private soot.Scene instance_soot_Scene;
    public soot.Scene soot_Scene() {
        if( instance_soot_Scene == null ) instance_soot_Scene = new soot.Scene( g );
        return instance_soot_Scene;
    }

    private soot.ShortType instance_soot_ShortType;
    public soot.ShortType soot_ShortType() {
        if( instance_soot_ShortType == null ) instance_soot_ShortType = new soot.ShortType( g );
        return instance_soot_ShortType;
    }

    private soot.jimple.toolkits.pointer.SideEffectTagger instance_soot_jimple_toolkits_pointer_SideEffectTagger;
    public soot.jimple.toolkits.pointer.SideEffectTagger soot_jimple_toolkits_pointer_SideEffectTagger() {
        if( instance_soot_jimple_toolkits_pointer_SideEffectTagger == null ) instance_soot_jimple_toolkits_pointer_SideEffectTagger = new soot.jimple.toolkits.pointer.SideEffectTagger( g );
        return instance_soot_jimple_toolkits_pointer_SideEffectTagger;
    }

    private soot.StmtAddressType instance_soot_StmtAddressType;
    public soot.StmtAddressType soot_StmtAddressType() {
        if( instance_soot_StmtAddressType == null ) instance_soot_StmtAddressType = new soot.StmtAddressType( g );
        return instance_soot_StmtAddressType;
    }

    private soot.Timers instance_soot_Timers;
    public soot.Timers soot_Timers() {
        if( instance_soot_Timers == null ) instance_soot_Timers = new soot.Timers( g );
        return instance_soot_Timers;
    }

    private soot.jimple.toolkits.typing.TypeAssigner instance_soot_jimple_toolkits_typing_TypeAssigner;
    public soot.jimple.toolkits.typing.TypeAssigner soot_jimple_toolkits_typing_TypeAssigner() {
        if( instance_soot_jimple_toolkits_typing_TypeAssigner == null ) instance_soot_jimple_toolkits_typing_TypeAssigner = new soot.jimple.toolkits.typing.TypeAssigner( g );
        return instance_soot_jimple_toolkits_typing_TypeAssigner;
    }

    private soot.jimple.toolkits.scalar.UnconditionalBranchFolder instance_soot_jimple_toolkits_scalar_UnconditionalBranchFolder;
    public soot.jimple.toolkits.scalar.UnconditionalBranchFolder soot_jimple_toolkits_scalar_UnconditionalBranchFolder() {
        if( instance_soot_jimple_toolkits_scalar_UnconditionalBranchFolder == null ) instance_soot_jimple_toolkits_scalar_UnconditionalBranchFolder = new soot.jimple.toolkits.scalar.UnconditionalBranchFolder( g );
        return instance_soot_jimple_toolkits_scalar_UnconditionalBranchFolder;
    }

    private soot.UnknownType instance_soot_UnknownType;
    public soot.UnknownType soot_UnknownType() {
        if( instance_soot_UnknownType == null ) instance_soot_UnknownType = new soot.UnknownType( g );
        return instance_soot_UnknownType;
    }

    private soot.jimple.toolkits.scalar.UnreachableCodeEliminator instance_soot_jimple_toolkits_scalar_UnreachableCodeEliminator;
    public soot.jimple.toolkits.scalar.UnreachableCodeEliminator soot_jimple_toolkits_scalar_UnreachableCodeEliminator() {
        if( instance_soot_jimple_toolkits_scalar_UnreachableCodeEliminator == null ) instance_soot_jimple_toolkits_scalar_UnreachableCodeEliminator = new soot.jimple.toolkits.scalar.UnreachableCodeEliminator( g );
        return instance_soot_jimple_toolkits_scalar_UnreachableCodeEliminator;
    }

    private soot.toolkits.scalar.UnusedLocalEliminator instance_soot_toolkits_scalar_UnusedLocalEliminator;
    public soot.toolkits.scalar.UnusedLocalEliminator soot_toolkits_scalar_UnusedLocalEliminator() {
        if( instance_soot_toolkits_scalar_UnusedLocalEliminator == null ) instance_soot_toolkits_scalar_UnusedLocalEliminator = new soot.toolkits.scalar.UnusedLocalEliminator( g );
        return instance_soot_toolkits_scalar_UnusedLocalEliminator;
    }

    private soot.coffi.UnusuableType instance_soot_coffi_UnusuableType;
    public soot.coffi.UnusuableType soot_coffi_UnusuableType() {
        if( instance_soot_coffi_UnusuableType == null ) instance_soot_coffi_UnusuableType = new soot.coffi.UnusuableType( g );
        return instance_soot_coffi_UnusuableType;
    }

    private soot.VoidType instance_soot_VoidType;
    public soot.VoidType soot_VoidType() {
        if( instance_soot_VoidType == null ) instance_soot_VoidType = new soot.VoidType( g );
        return instance_soot_VoidType;
    }

    private soot.EntryPoints instance_soot_EntryPoints;
    public soot.EntryPoints soot_EntryPoints() {
        if( instance_soot_EntryPoints == null ) instance_soot_EntryPoints = new soot.EntryPoints( g );
        return instance_soot_EntryPoints;
    }

    private soot.jimple.toolkits.annotation.callgraph.CallGraphTagger instance_soot_jimple_toolkits_annotation_callgraph_CallGraphTagger;
    public soot.jimple.toolkits.annotation.callgraph.CallGraphTagger soot_jimple_toolkits_annotation_callgraph_CallGraphTagger() {
        if( instance_soot_jimple_toolkits_annotation_callgraph_CallGraphTagger == null ) instance_soot_jimple_toolkits_annotation_callgraph_CallGraphTagger = new soot.jimple.toolkits.annotation.callgraph.CallGraphTagger( g );
        return instance_soot_jimple_toolkits_annotation_callgraph_CallGraphTagger;
    }

    private soot.jimple.toolkits.annotation.nullcheck.NullPointerColorer instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerColorer;
    public soot.jimple.toolkits.annotation.nullcheck.NullPointerColorer soot_jimple_toolkits_annotation_nullcheck_NullPointerColorer() {
        if( instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerColorer == null ) instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerColorer = new soot.jimple.toolkits.annotation.nullcheck.NullPointerColorer( g );
        return instance_soot_jimple_toolkits_annotation_nullcheck_NullPointerColorer;
    }

    private soot.jimple.toolkits.annotation.parity.ParityTagger instance_soot_jimple_toolkits_annotation_parity_ParityTagger;
    public soot.jimple.toolkits.annotation.parity.ParityTagger soot_jimple_toolkits_annotation_parity_ParityTagger() {
        if( instance_soot_jimple_toolkits_annotation_parity_ParityTagger == null ) instance_soot_jimple_toolkits_annotation_parity_ParityTagger = new soot.jimple.toolkits.annotation.parity.ParityTagger( g );
        return instance_soot_jimple_toolkits_annotation_parity_ParityTagger;
    }

    private soot.jimple.toolkits.annotation.methods.UnreachableMethodsTagger instance_soot_jimple_toolkits_annotation_methods_UnreachableMethodsTagger;
    public soot.jimple.toolkits.annotation.methods.UnreachableMethodsTagger soot_jimple_toolkits_annotation_methods_UnreachableMethodsTagger() {
        if( instance_soot_jimple_toolkits_annotation_methods_UnreachableMethodsTagger == null ) instance_soot_jimple_toolkits_annotation_methods_UnreachableMethodsTagger = new soot.jimple.toolkits.annotation.methods.UnreachableMethodsTagger( g );
        return instance_soot_jimple_toolkits_annotation_methods_UnreachableMethodsTagger;
    }

    private soot.jimple.toolkits.annotation.fields.UnreachableFieldsTagger instance_soot_jimple_toolkits_annotation_fields_UnreachableFieldsTagger;
    public soot.jimple.toolkits.annotation.fields.UnreachableFieldsTagger soot_jimple_toolkits_annotation_fields_UnreachableFieldsTagger() {
        if( instance_soot_jimple_toolkits_annotation_fields_UnreachableFieldsTagger == null ) instance_soot_jimple_toolkits_annotation_fields_UnreachableFieldsTagger = new soot.jimple.toolkits.annotation.fields.UnreachableFieldsTagger( g );
        return instance_soot_jimple_toolkits_annotation_fields_UnreachableFieldsTagger;
    }

    private soot.jimple.toolkits.annotation.qualifiers.TightestQualifiersTagger instance_soot_jimple_toolkits_annotation_qualifiers_TightestQualifiersTagger;
    public soot.jimple.toolkits.annotation.qualifiers.TightestQualifiersTagger soot_jimple_toolkits_annotation_qualifiers_TightestQualifiersTagger() {
        if( instance_soot_jimple_toolkits_annotation_qualifiers_TightestQualifiersTagger == null ) instance_soot_jimple_toolkits_annotation_qualifiers_TightestQualifiersTagger = new soot.jimple.toolkits.annotation.qualifiers.TightestQualifiersTagger( g );
        return instance_soot_jimple_toolkits_annotation_qualifiers_TightestQualifiersTagger;
    }

    private soot.jimple.toolkits.pointer.ParameterAliasTagger instance_soot_jimple_toolkits_pointer_ParameterAliasTagger;
    public soot.jimple.toolkits.pointer.ParameterAliasTagger soot_jimple_toolkits_pointer_ParameterAliasTagger() {
        if( instance_soot_jimple_toolkits_pointer_ParameterAliasTagger == null ) instance_soot_jimple_toolkits_pointer_ParameterAliasTagger = new soot.jimple.toolkits.pointer.ParameterAliasTagger( g );
        return instance_soot_jimple_toolkits_pointer_ParameterAliasTagger;
    }

    private soot.jimple.toolkits.annotation.defs.ReachingDefsTagger instance_soot_jimple_toolkits_annotation_defs_ReachingDefsTagger;
    public soot.jimple.toolkits.annotation.defs.ReachingDefsTagger soot_jimple_toolkits_annotation_defs_ReachingDefsTagger() {
        if( instance_soot_jimple_toolkits_annotation_defs_ReachingDefsTagger == null ) instance_soot_jimple_toolkits_annotation_defs_ReachingDefsTagger = new soot.jimple.toolkits.annotation.defs.ReachingDefsTagger( g );
        return instance_soot_jimple_toolkits_annotation_defs_ReachingDefsTagger;
    }

    private soot.jimple.toolkits.annotation.liveness.LiveVarsTagger instance_soot_jimple_toolkits_annotation_liveness_LiveVarsTagger;
    public soot.jimple.toolkits.annotation.liveness.LiveVarsTagger soot_jimple_toolkits_annotation_liveness_LiveVarsTagger() {
        if( instance_soot_jimple_toolkits_annotation_liveness_LiveVarsTagger == null ) instance_soot_jimple_toolkits_annotation_liveness_LiveVarsTagger = new soot.jimple.toolkits.annotation.liveness.LiveVarsTagger( g );
        return instance_soot_jimple_toolkits_annotation_liveness_LiveVarsTagger;
    }

    private soot.toolkits.graph.interaction.InteractionHandler instance_soot_toolkits_graph_interaction_InteractionHandler;
    public soot.toolkits.graph.interaction.InteractionHandler soot_toolkits_graph_interaction_InteractionHandler() {
        if( instance_soot_toolkits_graph_interaction_InteractionHandler == null ) instance_soot_toolkits_graph_interaction_InteractionHandler = new soot.toolkits.graph.interaction.InteractionHandler( g );
        return instance_soot_toolkits_graph_interaction_InteractionHandler;
    }

    private soot.jimple.toolkits.annotation.logic.LoopInvariantFinder instance_soot_jimple_toolkits_annotation_logic_LoopInvariantFinder;
    public soot.jimple.toolkits.annotation.logic.LoopInvariantFinder soot_jimple_toolkits_annotation_logic_LoopInvariantFinder() {
        if( instance_soot_jimple_toolkits_annotation_logic_LoopInvariantFinder == null ) instance_soot_jimple_toolkits_annotation_logic_LoopInvariantFinder = new soot.jimple.toolkits.annotation.logic.LoopInvariantFinder( g );
        return instance_soot_jimple_toolkits_annotation_logic_LoopInvariantFinder;
    }

    private soot.jimple.toolkits.annotation.AvailExprTagger instance_soot_jimple_toolkits_annotation_AvailExprTagger;
    public soot.jimple.toolkits.annotation.AvailExprTagger soot_jimple_toolkits_annotation_AvailExprTagger() {
        if( instance_soot_jimple_toolkits_annotation_AvailExprTagger == null ) instance_soot_jimple_toolkits_annotation_AvailExprTagger = new soot.jimple.toolkits.annotation.AvailExprTagger( g );
        return instance_soot_jimple_toolkits_annotation_AvailExprTagger;
    }

    private soot.toolkits.exceptions.ThrowableSet.Manager instance_soot_toolkits_exceptions_ThrowableSet_Manager;
    public soot.toolkits.exceptions.ThrowableSet.Manager soot_toolkits_exceptions_ThrowableSet_Manager() {
        if( instance_soot_toolkits_exceptions_ThrowableSet_Manager == null ) instance_soot_toolkits_exceptions_ThrowableSet_Manager = new soot.toolkits.exceptions.ThrowableSet.Manager( g );
        return instance_soot_toolkits_exceptions_ThrowableSet_Manager;
    }

    private soot.toolkits.exceptions.UnitThrowAnalysis instance_soot_toolkits_exceptions_UnitThrowAnalysis;
    public soot.toolkits.exceptions.UnitThrowAnalysis soot_toolkits_exceptions_UnitThrowAnalysis() {
        if( instance_soot_toolkits_exceptions_UnitThrowAnalysis == null ) instance_soot_toolkits_exceptions_UnitThrowAnalysis = new soot.toolkits.exceptions.UnitThrowAnalysis( g );
        return instance_soot_toolkits_exceptions_UnitThrowAnalysis;
    }

    private soot.toolkits.exceptions.PedanticThrowAnalysis instance_soot_toolkits_exceptions_PedanticThrowAnalysis;
    public soot.toolkits.exceptions.PedanticThrowAnalysis soot_toolkits_exceptions_PedanticThrowAnalysis() {
        if( instance_soot_toolkits_exceptions_PedanticThrowAnalysis == null ) instance_soot_toolkits_exceptions_PedanticThrowAnalysis = new soot.toolkits.exceptions.PedanticThrowAnalysis( g );
        return instance_soot_toolkits_exceptions_PedanticThrowAnalysis;
    }

    private soot.toolkits.exceptions.TrapTightener instance_soot_toolkits_exceptions_TrapTightener;
    public soot.toolkits.exceptions.TrapTightener soot_toolkits_exceptions_TrapTightener() {
        if( instance_soot_toolkits_exceptions_TrapTightener == null ) instance_soot_toolkits_exceptions_TrapTightener = new soot.toolkits.exceptions.TrapTightener( g );
        return instance_soot_toolkits_exceptions_TrapTightener;
    }

    private soot.jimple.toolkits.annotation.callgraph.CallGraphGrapher instance_soot_jimple_toolkits_annotation_callgraph_CallGraphGrapher;
    public soot.jimple.toolkits.annotation.callgraph.CallGraphGrapher soot_jimple_toolkits_annotation_callgraph_CallGraphGrapher() {
        if( instance_soot_jimple_toolkits_annotation_callgraph_CallGraphGrapher == null ) instance_soot_jimple_toolkits_annotation_callgraph_CallGraphGrapher = new soot.jimple.toolkits.annotation.callgraph.CallGraphGrapher( g );
        return instance_soot_jimple_toolkits_annotation_callgraph_CallGraphGrapher;
    }

    private soot.SootResolver instance_soot_SootResolver;
    public soot.SootResolver soot_SootResolver() {
        if( instance_soot_SootResolver == null ) instance_soot_SootResolver = new soot.SootResolver( g );
        return instance_soot_SootResolver;
    }

    private soot.jimple.toolkits.annotation.DominatorsTagger instance_soot_jimple_toolkits_annotation_DominatorsTagger;
    public soot.jimple.toolkits.annotation.DominatorsTagger soot_jimple_toolkits_annotation_DominatorsTagger() {
        if( instance_soot_jimple_toolkits_annotation_DominatorsTagger == null ) instance_soot_jimple_toolkits_annotation_DominatorsTagger = new soot.jimple.toolkits.annotation.DominatorsTagger( g );
        return instance_soot_jimple_toolkits_annotation_DominatorsTagger;
    }

    private soot.jimple.toolkits.annotation.purity.PurityAnalysis instance_soot_jimple_toolkits_annotation_purity_PurityAnalysis;
    public soot.jimple.toolkits.annotation.purity.PurityAnalysis soot_jimple_toolkits_annotation_purity_PurityAnalysis() {
        if( instance_soot_jimple_toolkits_annotation_purity_PurityAnalysis == null ) instance_soot_jimple_toolkits_annotation_purity_PurityAnalysis = new soot.jimple.toolkits.annotation.purity.PurityAnalysis( g );
        return instance_soot_jimple_toolkits_annotation_purity_PurityAnalysis;
    }

//    private soot.javaToJimple.toolkits.GotoEliminator instance_soot_javaToJimple_toolkits_GotoEliminator;
//    public soot.javaToJimple.toolkits.GotoEliminator soot_javaToJimple_toolkits_GotoEliminator() {
//        if( instance_soot_javaToJimple_toolkits_GotoEliminator == null ) instance_soot_javaToJimple_toolkits_GotoEliminator = new soot.javaToJimple.toolkits.GotoEliminator( g );
//        return instance_soot_javaToJimple_toolkits_GotoEliminator;
//    }

    private soot.jimple.toolkits.annotation.j5anno.AnnotationGenerator instance_soot_jimple_toolkits_annotation_j5anno_AnnotationGenerator;
    public soot.jimple.toolkits.annotation.j5anno.AnnotationGenerator soot_jimple_toolkits_annotation_j5anno_AnnotationGenerator() {
        if( instance_soot_jimple_toolkits_annotation_j5anno_AnnotationGenerator == null ) instance_soot_jimple_toolkits_annotation_j5anno_AnnotationGenerator = new soot.jimple.toolkits.annotation.j5anno.AnnotationGenerator( g );
        return instance_soot_jimple_toolkits_annotation_j5anno_AnnotationGenerator;
    }

}
